input("-------- BEM - VINDO--------")
pro1 = input("Digite o nome d produto:")
pro1q = int (input("Qual a quantidade ?"))
pro1v = int(input("Qual o valor unitário de ?"))
input("-----------------------------------------------------")
pro2 = input("Digite o nome do produto:")
pro2q = int (input("Qual a quantidade de ?"))
pro2v = int(input("Qual o valor unitário de ?"))
input("-----------------------------------------------------")
pro3 = input("Digite o nome do produto:")
pro3q = int(input("Qual a quantidade de ?"))
pro3v = int(input("Qual o valor unitário de ?"))
input("-----------------------------------------------------")
totalpd = ((pro1q*pro1v) + (pro2q*pro2v) + (pro3q*pro3v))
print(f"Total: R$ {totalpd}")
